Repository Pda5th-SolZipMoa/front, pull requests merged in 2024-12, with the labels that each got.

#20 Feat/#19 side detail page
  public/side_detail_gpt.png
  src/pages/side_detail/ChatGPT.jsx
  src/pages/side_detail/Discussion.jsx
  src/pages/side_detail/GPTSummary.jsx
  src/pages/side_detail/InvestmentInfo.jsx
  src/pages/side_detail/NearbySolHomes.jsx
  src/pages/side_detail/NewsSection.jsx
  src/pages/side_detail/PriceHistory.jsx
  src/pages/side_detail/PropertyDetail.jsx
  src/pages/side_detail/PropertyHeader.jsx
  src/pages/side_detail/RealEstatePage.jsx
  src/routers/AppRouter.jsx
Labels: 구현

#23 사용자 주문 화면 데이터 프론트엔드 렌더링 구현
  src/pages/property_detail/trade/TradeBoard.jsx
  src/pages/property_detail/trade/TradeMain.jsx
  src/pages/property_detail/trade/TradeOptionsBox.jsx
  src/pages/property_detail/trade/TradeOrderForm.jsx
Labels: 구현

#25 부동산 토큰발행페이지 디테일 구분
  src/pages/property_create/FormContents.jsx
  src/pages/property_create/FormIndex.jsx
  src/pages/property_create/FormPhoto.jsx
  src/pages/property_detail/info/DetailBox.jsx
  src/pages/property_detail/info/DetailCategory.jsx
  src/pages/property_detail/info/DetailIndex.jsx
Labels: 구현

#26 건물 단일가매매 기록 프론트엔드 렌더링 구현
  src/pages/property_detail/trade/TradeGraph.jsx
Labels: 구현

#27 feat: 사이드 디테일 페이지 뉴스 및 토론방 UI 구현 #19
  package.json
  src/pages/side_detail/Discussion.jsx
  src/pages/side_detail/NewsSection.jsx
Labels: 구현

#30 마이페이지 구현
  package.json
  src/components/header/Header.jsx
  src/pages/mypage/MyAsset.jsx
  src/pages/mypage/MyHoldings.jsx
  src/pages/mypage/MyPage.css
  src/pages/mypage/MyPage.jsx
  src/pages/mypage/OrderHistory.jsx
  src/pages/mypage/OwnershipContext.jsx
  src/pages/mypage/PendingOrders.jsx
  src/pages/mypage/Portfolio.jsx
  src/routers/AppRouter.jsx
Labels: 구현

#34 Feat/#19 side detail page
  src/pages/property_detail/info/DetailIndex.jsx
  src/pages/side_detail/ChatGPT.jsx
  src/pages/side_detail/GPTSummary.jsx
  src/pages/side_detail/InvestmentInfo.jsx
  src/pages/side_detail/NewsSection.jsx
  src/pages/side_detail/PropertyDetail.jsx
  src/pages/side_detail/PropertyHeader.jsx
  src/pages/side_detail/RealEstatePage.jsx
Labels: 구현

#35 feat: 오류 수정 #19
  src/pages/side_detail/RealEstatePage.jsx
Labels: 구현

#36 feat: cicd 구현 #32
  .github/workflows/deploy.yml
Labels: 구현

#37 feat: UI 마무리 수정 #19
  src/pages/side_detail/Discussion.jsx
  src/pages/side_detail/PriceHistory.jsx
  src/pages/side_detail/PropertyDetail.jsx
  src/pages/side_detail/PropertyHeader.jsx
  src/pages/side_detail/RealEstatePage.jsx
Labels: 구현

#43 refactor: 메인 페이지 건물 리스트 내용 수정
  src/pages/main/PropertyCard.jsx
  src/pages/main/PropertyList.jsx
Labels: 구현

#44 fix: 토큰 발행 페이지 발행 안되는 오류 (#42)
  src/hooks/myToken.json
  src/pages/property_create/FormIndex.jsx
  src/pages/property_detail/info/DetailCategory.jsx
Labels: 버그수정

#46 토큰 거래 페이지 주문 수량 제한 및 기본 가격 설정 기능 추가
  src/pages/property_detail/trade/TradeContext.jsx
  src/pages/property_detail/trade/TradeGraph.jsx
  src/pages/property_detail/trade/TradeMain.jsx
  src/pages/property_detail/trade/TradeOrderForm.jsx
Labels: 구현

#49 전체적인 버그 및 디자인 수정
  public/coin_logo.png
  public/mypage_icon.png
  src/components/header/Header.jsx
  src/pages/main/MainPage.jsx
  src/pages/mypage/MyPage.css
  src/pages/mypage/MyPage.jsx
  src/pages/property_create/FormIndex.jsx
  src/pages/property_detail/trade/TradeMain.jsx
  src/pages/property_detail/trade/TradeOptionsBox.jsx
  src/pages/side_detail/ChatGPT.jsx
  src/pages/side_detail/GPTSummary.jsx
  src/pages/side_detail/InvestmentInfo.jsx
  src/pages/side_detail/NewsSection.jsx
  src/pages/side_detail/RealEstatePage.jsx
Labels: 버그수정, 디자인

#47 owner id 프론트에서 삭제
  src/pages/property_create/FormIndex.jsx
Labels: 구현

#51 청약 페이지를 구현했습니다.
  src/pages/mypage/MyPage.jsx
  src/pages/mypage/SubscriptionHistory.jsx
  src/pages/property_detail/info/DetailBox.jsx
  src/pages/property_detail/info/DetailIndex.jsx
Labels: 구현

#52 feat: UI 디자인 수정 (#38)
  src/App.jsx
  src/pages/side_detail/ChatGPT.css
  src/pages/side_detail/ChatGPT.jsx
  src/pages/side_detail/GPTSummary.css
  src/pages/side_detail/GPTSummary.jsx
  src/pages/side_detail/InvestmentInfo.css
  src/pages/side_detail/InvestmentInfo.jsx
  src/pages/side_detail/NewsSection.css
  src/pages/side_detail/NewsSection.jsx
  src/pages/side_detail/PropertyHeader.css
  src/pages/side_detail/PropertyHeader.jsx
  src/pages/side_detail/RealEstatePage.jsx
Labels: 구현, 디자인

#55 3 메인 페이지 구현
  src/components/map/Map.jsx
  src/pages/main/MainPage.jsx
  src/pages/main/PropertyCard.jsx
Labels: 버그수정

#56 3 메인 페이지 구현
  package.json
  src/components/map/Map.jsx
  src/pages/main/MainPage.jsx
  src/pages/main/PropertyCard.jsx
  src/pages/main/PropertyList.jsx
Labels: 구현

#58 feat: 메인 페이지 및 기타 라우팅 페이지 수정 (#3)
  src/components/header/Header.jsx
  src/components/map/Map.jsx
  src/pages/main/MainPage.jsx
  src/pages/main/PropertyCard.jsx
  src/pages/main/PropertyList.jsx
  src/pages/property_detail/info/DetailBox.jsx
  src/pages/property_detail/info/DetailCategory.jsx
  src/pages/property_detail/info/DetailIndex.jsx
  src/pages/side_detail/InvestmentInfo.jsx
  src/routers/AppRouter.jsx
Labels: 버그수정, 구현

#59 3 메인 페이지 구현
  package.json
  src/components/map/Map.jsx
  src/pages/main/PropertyList.jsx
  src/pages/property_detail/info/DetailBox.jsx
  src/pages/property_detail/info/ScheduleButton.jsx
  src/pages/side_detail/InvestmentInfo.jsx
Labels: 버그수정, 구현, 디자인
